name: Deploy Infra on AWS CloudFormation

on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
      template-path:
        required: true
        type: string
      template-parameters-path:
        required: false
        type: string
        default: 'template-parameters.json'
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
    outputs:
      cloud-formation-result:
        description: "Resultado da tentativa de deploy CloudFormation"
        value: ${{ jobs.deploy-cloud-formation.outputs.cloud-formation-result }}

permissions:
  contents: read

jobs:

  generate-basic-constants:
    uses: devsuperior/dsc-shared-pipelines/.github/workflows/generate-basic-constants.yml@main

  generate-complete-template-parameters-app-config:
    needs: generate-basic-constants
    uses: devsuperior/dsc-shared-pipelines/.github/workflows/generate-complete-template-parameters-app-config.yml@main
    with:
      template-parameters-path: ${{ inputs.template-parameters-path }}
      environment-name: ${{ needs.generate-basic-constants.outputs.environment-name }}
      repository-name: ${{ needs.generate-basic-constants.outputs.repository-name }}

  check-delete-cloud-formation-status:
    needs: generate-basic-constants
    uses: devsuperior/dsc-shared-pipelines/.github/workflows/check-delete-cloud-formation-status.yml@main
    with:
      aws-region: ${{ inputs.aws-region }}
      stack-name: ${{ needs.generate-basic-constants.outputs.stack-name }}
    secrets:
      aws-access-key-id: ${{ secrets.aws-access-key-id }}
      aws-secret-access-key: ${{ secrets.aws-secret-access-key }}

  check-app-config-status:
    needs: check-delete-cloud-formation-status
    uses: devsuperior/dsc-shared-pipelines/.github/workflows/check-app-config-status.yml@main
    with:
      aws-region: ${{ inputs.aws-region }}
      repository-name: ${{ needs.generate-basic-constants.outputs.repository-name }}
      environment-name: ${{ needs.generate-basic-constants.outputs.environment-name }}
    secrets:
      aws-access-key-id: ${{ secrets.aws-access-key-id }}
      aws-secret-access-key: ${{ secrets.aws-secret-access-key }}

  deploy-cloud-formation:
    needs: [check-delete-cloud-formation-status, generate-complete-template-parameters-app-config, generate-basic-constants, check-app-config-status]
    if: ${{ needs.check-app-config-status.outputs.requires-cloudformation }}
    uses: devsuperior/dsc-shared-pipelines/.github/workflows/deploy-cloud-formation.yml@main
    with:
      aws-region: ${{ inputs.aws-region }}
      template-path: ${{ inputs.template-path }}
      template-parameters-path: ${{ inputs.template-parameters-path }}
      stack-name: ${{ needs.generate-basic-constants.outputs.stack-name }}
      complete-template-parameters-base64: ${{ needs.generate-complete-template-parameters-app-config.outputs.complete-template-parameters-base64 }}
    secrets:
      aws-access-key-id: ${{ secrets.aws-access-key-id }}
      aws-secret-access-key: ${{ secrets.aws-secret-access-key }}

    

