name: Deploy on AWS CloudFormation

on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
      template-path:
        required: true
        type: string
      template-parameters-path:
        required: true
        type: string
      stack-name:
        required: true
        type: string
      complete-template-parameters-base64:
        required: true
        type: string
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
    outputs:
      cloud-formation-result:
        description: "Resultado da tentativa de deploy CloudFormation"
        value: ${{ jobs.deploy.outputs.output1 }}

permissions:
  contents: read

jobs:
  deploy:
    name: Submit to AWS CloudFormation
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.deploy-script.outputs.cloud-formation-result }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ inputs.aws-region }}

      - name: Deploy CloudFormation stack
        id: deploy-script
        run: |
          echo "Iniciando script de Deploy no Cloud Formation."

          echo "${{ inputs.complete-template-parameters-base64 }}" | base64 -d > ${{ inputs.template-parameters-path }}

          echo "Conteudo do arquivo de parametros: $(cat ${{ inputs.template-parameters-path }})"

          cloud_formation_result=$(aws cloudformation deploy \
              --stack-name ${{ inputs.stack-name }} \
              --template-file ${{ inputs.template-path }} \
              --parameter-overrides file://${{ inputs.template-parameters-path }} \
              --capabilities CAPABILITY_NAMED_IAM  2>&1 || true)        

          cloud_formation_result=$(echo "$cloud_formation_result" | tr 'A-Z' 'a-z')

          echo "Resultado do pedido de deploy: $cloud_formation_result"

          if [[ ! $cloud_formation_result == *"Successfully created/updated stack"* || ! $cloud_formation_result == *"No changes to deploy"* ]]; then
            echo "Falha na criacao da stack. Saindo..."
            exit 1
          fi

          echo "cloud-formation-result=$(echo $cloud_formation_result | tr '\n' ' ')" >> $GITHUB_OUTPUT
