name: Deploy EC2

on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
      template-path:
        required: true
        type: string
      template-parameters-path:
        required: true
        type: string
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true

permissions:
  contents: read

jobs:

  build-basic-constants:
    uses: devsuperior/dsc-shared-pipelines/.github/workflows/sub-pipeline-setup-basic-constants.yml@main

  build-template-parameters:
    needs: build-basic-constants
    uses: devsuperior/dsc-shared-pipelines/.github/workflows/sub-pipeline-build-complete-template-parameters.yml@main
    with:
      template-parameters-path: ${{ inputs.template-parameters-path }}
      environment-name: ${{ needs.build-basic-constants.outputs.environment-name }}
      repository-name: ${{ needs.build-basic-constants.outputs.repository-name }}

  verify-stack-on-cloud-formation:
    needs: build-basic-constants
    uses: devsuperior/dsc-shared-pipelines/.github/workflows/sub-pipeline-check-cloud-formation-stack-status-and-delete-if-necessary.yml@main
    with:
      aws-region: ${{ inputs.aws-region }}
      stack-name: ${{ needs.build-basic-constants.outputs.stack-name }}
    secrets:
      aws-access-key-id: ${{ secrets.aws-access-key-id }}
      aws-secret-access-key: ${{ secrets.aws-secret-access-key }}

  deploy:
    name: Deploy on AWS CloudFormation
    runs-on: ubuntu-latest
    needs: [verify-stack-on-cloud-formation, build-template-parameters]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ inputs.aws-region }}

      - name: Deploy CloudFormation stack
        run: |
          echo "Iniciando script de Deploy no Cloud Formation."

          echo "${{ needs.build-template-parameters.outputs.complete-template-parameters-base64 }}" | base64 -d > ${{ inputs.template-parameters-path }}

          echo "Conteudo do arquivo de parametros: $(cat ${{ inputs.template-parameters-path }})"

          cloud_formation_result=$(aws cloudformation deploy \
              --stack-name ${{ needs.build-basic-constants.outputs.stack-name }} \
              --template-file ${{ inputs.template-path }} \
              --parameter-overrides file://${{ inputs.template-parameters-path }} \
              --capabilities CAPABILITY_NAMED_IAM 2>&1)

          echo "Resultado do pedido de deploy: $cloud_formation_result"
