name: Deploy EC2

on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
      template-path:
        required: true
        type: string
      template-parameters-path:
        required: true
        type: string
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true

permissions:
  contents: read

jobs:

  build-env-vars:
    uses: devsuperior/dsc-shared-pipelines/.github/workflows/sub-pipeline-setup-basic-environment-variables.yml@main

  test:
    runs-on: ubuntu-latest
    needs: build-env-vars
    steps:
      - name: testando
        run: |
          echo "Testando"
          echo "REPOSITORY_NAME: ${{ needs.build-env-vars.outputs.REPOSITORY_NAME }}"
          echo "ENVIRONMENT_NAME: ${{ needs.build-env-vars.outputs.ENVIRONMENT_NAME }}"
          echo "STACK_NAME: ${{ needs.build-env-vars.outputs.STACK_NAME }}"

  build-template-parameters:
    needs: build-env-vars
    uses: devsuperior/dsc-shared-pipelines/.github/workflows/sub-pipeline-build-complete-template-parameters.yml@main
    with:
      template-parameters-path: ${{ inputs.template-parameters-path }}
      repository-name: ${{ needs.build-env-vars.outputs.REPOSITORY_NAME }}
      environment-name: ${{ needs.build-env-vars.outputs.ENVIRONMENT_NAME }}

  verify-stack-on-cloud-formation:
    needs: build-env-vars
    uses: devsuperior/dsc-shared-pipelines/.github/workflows/sub-pipeline-check-cloud-formation-stack-status-and-delete-if-necessary.yml@main
    with:
      aws-region: ${{ inputs.aws-region }}
      stack-name: ${{ needs.build-env-vars.outputs.STACK_NAME }}
    secrets:
      aws-access-key-id: ${{ secrets.aws-access-key-id }}
      aws-secret-access-key: ${{ secrets.aws-secret-access-key }}

  deploy:
    name: Deploy on AWS CloudFormation
    runs-on: ubuntu-latest
    needs: [verify-stack-on-cloud-formation, build-template-parameters]
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ inputs.aws-region }}

      - name: Deploy CloudFormation stack
        run: |
          echo "Iniciando script de Deploy no Cloud Formation."

          echo "${{ needs.build-template-parameters.outputs.COMPLETE_TEMPLATE_PARAMETERS }}" | base64 -d > ${{ inputs.template-parameters-path }}

          cloud_formation_result=$(aws cloudformation deploy \
              --stack-name ${{ needs.build-env-vars.outputs.STACK_NAME }} \
              --template-file ${{ inputs.template-path }} \
              --parameter-overrides file://${{ inputs.template-parameters-path }} \
              --capabilities CAPABILITY_NAMED_IAM 2>&1)

          echo "Resultado do pedido de deploy: $cloud_formation_result"
