name: Build application with Java Gradle

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Environments Vars from Template Parameters
        run: bash .github/workflows/scripts/setup-env-vars-template-params.sh

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build App
        run: ./gradlew build -x test --no-daemon