name: Deploy EC2

on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true

permissions:
  contents: read

jobs:
  build-env-vars:
    uses: devsuperior/dsc-shared-pipelines/.github/workflows/sub-pipeline-setup-basic-environment-variables.yml@main

  checkout-code:
    name: Checkout code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files in workflows directory
        run: ls -la ${{ github.action_path }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ inputs.aws-region }}

  build-template-parameters:
    - uses: .github/workflows/scripts/build-complete-template-parameters.sh

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Delete previous stack if necessary.
        env:
          STACK_NAME: stack-${{ github.ref_name }}-${{ github.event.repository.name }}
        run: .github/workflows/scripts/check-cloud-formation-stack-status-and-delete-if-necessary.sh

      - name: Deploy CloudFormation stack
        env:
          STACK_NAME: stack-${{ github.ref_name }}-${{ github.event.repository.name }}
        run: |
          echo "Iniciando script de Deploy no Cloud Formation."

          cloud_formation_result=$(aws cloudformation deploy \
              --stack-name $STACK_NAME \
              --template-file template.yml \
              --parameter-overrides file://complete-template-parameters.json \
              --capabilities CAPABILITY_NAMED_IAM 2>&1)

          echo "Resultado do pedido de deploy: $cloud_formation_result"
